version: 2

jobs:
  build:
    macos:
      xcode: "9.0"
    shell: /bin/bash --login -eo pipefail
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-bundle-cache-{{ checksum "script/ruby/Gemfile.lock" }}
        - macos-bundle-cache
    - run: |
        cd script/ruby/
        bundle install --path vendor/bundle
    - save_cache:
        key: macos-bundle-cache-{{ checksum "script/ruby/Gemfile.lock" }}
        paths:
        - script/ruby/vendor/bundle
    - run: |
        cd script/ruby/
        bundle exec ruby ./analyzer.rb --help
    # - run: script/build.sh
    - run: chruby-exec 2.4.2 -- script/analyze.sh
    - run: script/package.sh
    - persist_to_workspace:
        root: dist/
        paths:
        - gnupg-macos.tar.gz
    - store_artifacts:
        path: dist/

  deploy:
    docker:
    - image: circleci/ruby:2.4.2-node
    environment:
    - TARGET_PLATFORM=macos
    steps:
    - checkout
    - attach_workspace:
        at: dist/
    - restore_cache:
        keys:
        - linux-bundle-cache-{{ checksum "script/ruby/Gemfile.lock" }}
        - linux-bundle-cache
    - run: |
        cd script/ruby/
        bundle install --path vendor/bundle
    - save_cache:
        key: linux-bundle-cache-{{ checksum "script/ruby/Gemfile.lock" }}
        paths:
        - script/ruby/vendor/bundle
    - run: script/publish.sh

workflows:
  version: 2
  only:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - deploy:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/
